spring:
  datasource:
    url: ${DATABASE_URL}
    password: ${DATABASE_PASSWORD}
    username: ${DATABASE_ID}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
        default_batch_fetch_size: 100
    database: mysql

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    tags-sorter: alpha
    disable-swagger-default-url: true
    path: /swagger-ui
  paths-to-match: /api/**
