spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        highlight_sql: true
        show_sql: true
        format_sql: true
logging:
  level:
    org.hibernate.sql: info
    org.hibernate.type.descriptor.sql: trace